version: "3.8"

services:
  jeager-app:
    container_name: jeager-store
    build:
      context: ./src/
    ports:
      - "4000:80"
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - jeager-mysql
    environment:
      - MYSQL_HOST=jeager-mysql
      - MYSQL_USER=popcorn
      - MYSQL_PASSWORD=popcorn
      - MYSQL_DB=store
      - APP_ENV=dev
    cap_add:
      - SYS_ADMIN
    privileged: true    
    pid: "host"         

  jeager-mysql:
    build: ./database/
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=popcorn
      - MYSQL_DATABASE=store
      - MYSQL_PASSWORD=popcorn
